### ISSUE TITLE
Unable to run cgInstr.sh script

### ISSUE THREAD

**Issue by akshatgit** [saba96/droidcat#1]
Hi

I wanted to run the analyzer for my project, but I am getting some errors:
```
+ tee out-dynInstr-cg/instr-automatic.call.recorder.hd.real.all.superfree.Easy.pro.out
DUA-Forensics args to Soot: -w -cp /Users/akshatsinha/Documents/droidcat/libs/droidfax.jar:/libs/android.jar -p cg verbose:false,implicit-entry:true -p cg.spark verbose:false,on-fly-cg:true,rta:false -d /Users/akshatsinha/Documents/droidcat/cg.instrumented/ -process-dir /Users/akshatsinha/Documents/APKs_Analysis/PlayStore/y/automatic.call.recorder.hd.real.all.superfree.Easy.pro.apk
Soot started on Fri Jun 18 13:02:58 CDT 2021
java.lang.NullPointerException: Cannot invoke "String.split(String)" because the return value of "java.lang.System.getProperty(String)" is null
	at soot.JastAddJ.Program.initPaths(Program.java:350)
	at soot.SootResolver.<init>(SootResolver.java:88)
	at soot.Singletons.soot_SootResolver(Singletons.java:808)
	at soot.SootResolver.v(SootResolver.java:93)
	at soot.Scene.tryLoadClass(Scene.java:674)
	at soot.Scene.loadBasicClasses(Scene.java:1272)
	at soot.Scene.loadNecessaryClasses(Scene.java:1351)
	at soot.Main.run(Main.java:243)
	at soot.Main.main(Main.java:147)
	at dua.Forensics.main(Forensics.java:102)
	at dynCG.sceneInstr.main(sceneInstr.java:96)


Ouuups... something went wrong! Sorry about that.
Follow these steps to fix the problem:
1.) Are you sure you used the right command line?
    Click here to double-check:
    https://ssebuild.cased.de/nightly/soot/doc/soot_options.htm

2.) Not sure whether it's a bug? Feel free to discuss
    the issue on the Soot mailing list:
    https://github.com/Sable/soot/wiki/Getting-help

3.) Sure it's a bug? Click this link to report it.
    https://github.com/Sable/soot/issues/new?title=java.lang.NullPointerException+when+...&body=Steps+to+reproduce%3A%0A1.%29+...%0A%0AFiles+used+to+reproduce%3A+%0A...%0A%0ASoot+version%3A+%3Cpre%3Etrunk%3C%2Fpre%3E%0A%0ACommand+line%3A%0A%3Cpre%3E-w+-cp+%2FUsers%2Fakshatsinha%2FDocuments%2Fdroidcat%2Flibs%2Fdroidfax.jar%3A%2Flibs%2Fandroid.jar+-p+cg+verbose%3Afalse%2Cimplicit-entry%3Atrue+-p+cg.spark+verbose%3Afalse%2Con-fly-cg%3Atrue%2Crta%3Afalse+-d+%2FUsers%2Fakshatsinha%2FDocuments%2Fdroidcat%2Fcg.instrumented%2F+-process-dir+%2FUsers%2Fakshatsinha%2FDocuments%2FAPKs_Analysis%2FPlayStore%2Fy%2Fautomatic.call.recorder.hd.real.all.superfree.Easy.pro.apk%3C%2Fpre%3E%0A%0AMax+Memory%3A%0A%3Cpre%3E204800MB%3C%2Fpre%3E%0A%0AStack+trace%3A%0A%3Cpre%3Ejava.lang.NullPointerException%3A+Cannot+invoke+%26%2334%3BString.split%28String%29%26%2334%3B+because+the+return+value+of+%26%2334%3Bjava.lang.System.getProperty%28String%29%26%2334%3B+is+null%0A%09at+soot.JastAddJ.Program.initPaths%28Program.java%3A350%29%0A%09at+soot.SootResolver.%26%2360%3Binit%26%2362%3B%28SootResolver.java%3A88%29%0A%09at+soot.Singletons.soot_SootResolver%28Singletons.java%3A808%29%0A%09at+soot.SootResolver.v%28SootResolver.java%3A93%29%0A%09at+soot.Scene.tryLoadClass%28Scene.java%3A674%29%0A%09at+soot.Scene.loadBasicClasses%28Scene.java%3A1272%29%0A%09at+soot.Scene.loadNecessaryClasses%28Scene.java%3A1351%29%0A%09at+soot.Main.run%28Main.java%3A243%29%0A%09at+soot.Main.main%28Main.java%3A147%29%0A%09at+dua.Forensics.main%28Forensics.java%3A102%29%0A%09at+dynCG.sceneInstr.main%28sceneInstr.java%3A96%29%0A%3C%2Fpre%3E
    Please be as precise as possible when giving us
    information on how to reproduce the problem. Thanks!
```

Any help to run the analyzer for apks is appreciated!

Thanks 
Akshat

**Comment by saba96** [comment]
Hi @akshatgit,

Sorry for the super late reply. I missed your message. I was trying to reproduce the original paper result for my own, but unfortunately I could not reproduce their result! Hope you were able to fix it.

Best,
Saba
